// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu5Zq1x9syx2TdU6zc0lzUJ-Ma2guLYlM',
    appId: '1:850828629778:web:1f852969000b939fca05cb',
    messagingSenderId: '850828629778',
    projectId: 'omvote-4f543',
    authDomain: 'omvote-4f543.firebaseapp.com',
    storageBucket: 'omvote-4f543.appspot.com',
    measurementId: 'G-C0XHBYTCTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLOGwRi7_qdvmX_ylj0N_4nT1Z12RVulE',
    appId: '1:850828629778:android:6aeef0c8326ab482ca05cb',
    messagingSenderId: '850828629778',
    projectId: 'omvote-4f543',
    storageBucket: 'omvote-4f543.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmSPiMEFpUgKqtTxnum_x8FlNSHJtfijQ',
    appId: '1:850828629778:ios:3f2fa795a25d37f8ca05cb',
    messagingSenderId: '850828629778',
    projectId: 'omvote-4f543',
    storageBucket: 'omvote-4f543.appspot.com',
    iosBundleId: 'com.example.omvoting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmSPiMEFpUgKqtTxnum_x8FlNSHJtfijQ',
    appId: '1:850828629778:ios:3f2fa795a25d37f8ca05cb',
    messagingSenderId: '850828629778',
    projectId: 'omvote-4f543',
    storageBucket: 'omvote-4f543.appspot.com',
    iosBundleId: 'com.example.omvoting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu5Zq1x9syx2TdU6zc0lzUJ-Ma2guLYlM',
    appId: '1:850828629778:web:cce47f3e90db4afdca05cb',
    messagingSenderId: '850828629778',
    projectId: 'omvote-4f543',
    authDomain: 'omvote-4f543.firebaseapp.com',
    storageBucket: 'omvote-4f543.appspot.com',
    measurementId: 'G-JHJZ0MBEFQ',
  );
}
